server:
  port: 8080

#异步任务线程池配置
async:
  corePoolSize: 2
  maxPoolSize: 10
  queueSize: 1000

spring:
  #数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: abc123_
  cloud:
    gateway:
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: "http://localhost:7070"
#            allowedHeaders: "*"
#            allowedMethods:
#              - OPTIONS
#              - GET
#              - PUT
#              - POST
#              - DELETE
      routes:
          # id: 只是一个有意义的，唯一的名字，用于和其他route区分
        - id: first-service
          # uri: 请求将要被转发到的地方
          uri: http://localhost:8081/
          # predicates: 在什么条件下会转发。gateway只有在条件满足的情况下才会转发请求
          predicates:
              # 参看所有支持的predicate类型:
              # https://cloud.spring.io/spring-cloud-gateway/reference/html/#gateway-request-predicates-factories
            - Path=/first/**
          # filters: 可以在filter中，对request/response进行额外的处理
          # 注意：filter的执行顺序，就是声明的顺序
          filters:
              # 参看所有内置的GatewayFilter:
              # https://cloud.spring.io/spring-cloud-gateway/reference/html/#gatewayfilter-factories
            - LoggingFilter
            - AuthFilter
        - id: second-service
          uri: http://localhost:8082/
          predicates:
            - Path=/second/**
          filters:
            - AuthFilter
            - LoggingFilter
